
defaults:
  type: object
  properties:
    custom:
      type: object
      default: {}
    displayName:
      type: string
    links:
      title: Data Links
      type: array
      items:
        $ref: '_link.yml#/link'
    mappings:
      type: array
      items:
        $ref: '_mapping.yml#/mapping'
    max:
      type: integer
    min:
      type: integer
    noValue:
      type: string
    thresholds:
      $ref: '_threshold.yml#/threshold'
    unit:
      type: string

fieldConfig:
  type: object
  properties:
    defaults:
      $ref: '#/defaults'
    overrides:
      type: array
      items:
        $ref: '_override.yml#/override'
