openapi: 3.0.3

info:
  title: Grafana Dashboard Spec
  version: '8.5'

paths: {}

components:
  schemas:
    Dashboard:
      $ref: 'Dashboard.yml#/Dashboard'
    Panel:
      type: object
      properties:
        AlertGroups:
          $ref: 'panels/AlertGroups.yml#/AlertGroups'
        Gauge:
          $ref: 'panels/Gauge.yml#/Gauge'
        Graph:
          $ref: 'panels/Graph.yml#/Graph'
        Row:
          $ref: 'panels/Row.yml#/Row'
        Stat:
          $ref: 'panels/Stat.yml#/Stat'
        StateTimeline:
          $ref: 'panels/StateTimeline.yml#/StateTimeline'
        Table:
          $ref: 'panels/Table.yml#/Table'
        Text:
          $ref: 'panels/Text.yml#/Text'
    Target:
      type: object
      properties:
        Loki:
          $ref: 'targets/Loki.yml#/Loki'
        Prometheus:
          $ref: 'targets/Prometheus.yml#/Prometheus'
    Template:
      type: object
      properties:
        Custom:
          $ref: 'templates/Custom.yml#/Custom'
        Datasource:
          $ref: 'templates/Datasource.yml#/Datasource'
        Query:
          $ref: 'templates/Query.yml#/Query'
